stages:
  download_time_series:
    cmd: python repro/downloads/time_series/download_time_series_dataset.py
    deps:
    - repro/downloads/time_series/download_time_series_dataset.py
    outs:
    - data/ts/
  generate_toy_cloud_removal_dataset:
    cmd: source repro/toy-data/cloud_removal/generate_toy_cloud_removal_dataset.sh
    deps:
    - data/ts/Multivariate_ts/Epilepsy/Epilepsy_TEST.ts
    - data/ts/Multivariate_ts/Epilepsy/Epilepsy_TRAIN.ts
    - data/ts/Multivariate_ts/RacketSports/RacketSports_TEST.ts
    - data/ts/Multivariate_ts/RacketSports/RacketSports_TRAIN.ts
    - run_toy_derivation.py
    - run_toy_generation.py
    - src/toygeneration/config/cloud_removal/optical/derivation_clean_optical.yaml
    - src/toygeneration/config/cloud_removal/optical/derivation_clouded_optical.yaml
    - src/toygeneration/config/cloud_removal/optical/generation_latent_optical.yaml
    - src/toygeneration/config/cloud_removal/sar/derivation_sar.yaml
    - src/toygeneration/config/cloud_removal/sar/generation_latent_sar.yaml
    outs:
    - data/toy/cloud_removal/
